### ISSUE TITLE
Unhandled Error Caught

### ISSUE THREAD

**Issue by ZeroDot1** [pfbrowning/ng-radio#2]
Hi, I'm testing your online version of ng-radio, today was a bug.
I made a screenshot for you, I hope it helps you.
I will contribute more to your project as soon as I have some time.

Thanks for your good work, I really appreciate your project.

This error occurs if you click on Radio Browser.
![Bildschirmfoto vom 2019-05-11 11-51-48](https://user-images.githubusercontent.com/28985171/57568167-e6e44200-73e3-11e9-9f7e-d8570c03a9ad.png)

**Comment by pfbrowning** [comment]
Thanks for pointing this out, @ZeroDot1.   I accidentally broke the routing last week in the progress of re-organizing my components into lazy-loaded feature modules, but I found and fixed the issue a few days ago.

It should work properly for you now after a CTRL+F5.  If you still have problems after doing so, feel free to re-open this with more details.

**Comment by ZeroDot1** [comment]
Hi @pfbrowning,
Thanks for fixing the mistake.
At the moment there is only an error when loading the page for the first time, screenshot.
![Bildschirmfoto vom 2019-05-18 00-22-12](https://user-images.githubusercontent.com/28985171/57959223-06f39400-7903-11e9-824b-62c7dc155d22.png)
After a click on restart everything works normally.
